### ISSUE TITLE
ROS wrapper needed

### ISSUE THREAD

**Issue by naughtyStark** [APRIL-ZJU/CL-CBS#1]
Hi,

In your paper, you mention using ROS melodic for testing the system in the real world. Could you also upload the ROS-wrapper for your system?

Thanks

Regards,
Sidharth.

**Comment by ShenoyVaradaraya** [comment]
Hi ,
any luck finding the ROS wrapper or any alternative library?

**Comment by zijinoier** [comment]
A third-party ROS wrapper implemented by MuSHR can be found at https://github.com/prl-mushr/clcbs_ros/tree/178bfc731c88ca53140fd5fded37b3de5d4a6f07
